version: '3.7'
services:
  db:
    container_name: db_foodgram
    ports:
      - ${DB_PORT}:${DB_PORT}
    image: postgres:13-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    command: -p ${DB_PORT}

  backend:
    container_name: backend_foodgram
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    #    command: "gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --reload"
    command: "sh ./entrypoint.sh"
    volumes:
      - ../backend:/app
      - staticfiles:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - db

  frontend:
    container_name: frontend_foodgram
    image: v1tox/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    container_name: nginx_foodgram
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx.dev.conf:/etc/nginx/templates/default.conf.template
      - staticfiles:/var/html/static/
      - media:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend


volumes:
  staticfiles:
  media:
  db:
